ФП 13 - Shareit(add-controllers)
stasyaofit/java-shareit pull request #1
Opened 2023-07-13 13:51 UTC by stasyaofit

2023-07-14 13:48 UTC, AnastasiyaFomkina requested changes

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ResponseEntity handleMethodArgumentNotValidException(final MethodArgumentNotValidException e) {
Нужно параметризовать `ResponseEntity` здесь и ниже. Вот [тут](https://www.baeldung.com/raw-types-java) больше про то, почему плохо использовать `raw types`

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/IncorrectParameterException.java
> +    public IncorrectParameterException(String parameter) {
Можно заменить на `@AllArgsContructor` и `@Getter` от `lombok`, чтобы избавиться от однотипного кода

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
_Саморазвитие_
Чтобы максимально избавится от однотипного кода, очень удобно использовать [@RequiredArgsConstructor ](https://www.baeldung.com/spring-injection-lombok#:~:text=Constructor%20Injection%20With%20Lombok) из библиотеки `lombok`. Он автоматически заинжектит все нужные нам поля

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validateItem(Item item) {
Лучше заменить на [@Validated](https://reflectoring.io/bean-validation-with-spring-boot/#validated-and-valid:~:text=validating%20programmatically.-,%40Validated%20and%20%40Valid,-In%20many%20cases)

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        /* можно ли сюда вынести проверку почты следующим образом
Нужно! Можно еще ее оптимизировать. Чтобы проверка почты проходила за O(1), нужно завести Set, куда при добавлении нового пользователя мы будем класть его email. Соответственно, перед тем как добавить пользователя, нужно будет посмотреть, есть ли уже в сете подобный `email`, если есть - то пользователь с таким `email` уже существует. 

Так как поиск и вставка в сете работают в среднем за O(1), то наш алгоритм поиска одинаковых email тоже будет работать в среднем за O(1), а это гораздо быстрее, чем пройтись по всем элементам списка O(n)
![Временная сложность структур данных java](https://github.com/stasyaofit/java-shareit/assets/43168217/1af63f21-989f-4693-9d04-a39787ecb025)

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void validateUser(User user) {
Нужно заменить на `@Validated`

2023-07-14 13:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +import java.util.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-07-14 14:35 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ResponseEntity handleMethodArgumentNotValidException(final MethodArgumentNotValidException e) {
У меня изначально был свой класс  `ErrorResponse`  я его использовал в качестве параметра `ResponseEntity` ,  но ошибки с нужными кодами почему-то не отлавливались, как нужно. Использовал аннотацию класса `@RestControllerAdvice`. В чём может быть проблема?

2023-07-14 14:38 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validateItem(Item item) {
Я вас правильно понял? Сделать по подобию, как здесь? [https://www.baeldung.com/spring-valid-vs-validated](url)

2023-07-14 17:22 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ResponseEntity handleMethodArgumentNotValidException(final MethodArgumentNotValidException e) {
Решено.

2023-07-16 13:07 UTC, AnastasiyaFomkina approved these changes

2023-07-16 13:07 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    private final Set<String> userEmails = new HashSet<>();
👍

2023-07-16 15:58 UTC, merged