ФП-14 Shareit(add-bookings)
stasyaofit/java-shareit pull request #2
Opened 2023-07-26 22:34 UTC by stasyaofit

2023-07-27 09:20 UTC, AnastasiyaFomkina requested changes

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
И здесь тоже

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)
Проверь, пожалуйста, и убери из всех сущностей

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/comment/dto/CommentDto.java
> +    String text;
Нет модификатора доступа

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +import lombok.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (Item item : items) {
Нужно заменить на stream api

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/model/User.java
> -@Data
👍

2023-07-27 09:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/util/Constants.java
> +    public static final String REQUEST_HEADER = "X-Sharer-User-Id";
👍

2023-07-27 10:06 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/comment/dto/CommentDto.java
> +    String text;
Поправил.

2023-07-27 10:06 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +import lombok.*;
Скидывали,читал статью и настраивал. Видимо слетела настройка. Поправил.

2023-07-27 10:13 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
`@EqualsAndHashCode` тоже лучше убрать? В статье был такой совет.

2023-07-27 10:43 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
А " * " - что означает? ))

2023-07-27 18:40 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
Анастасия, попробую разобраться с цепочкой зависимостей , прикручу, к следующему спринту, как MapStruct к предыдущему.

2023-07-27 18:40 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (Item item : items) {
Сделано

2023-07-28 15:27 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
Задача со звездочкой = дополнительная задача на саморазвитие, их можно выполнять, если есть свободное время и желание

2023-07-28 15:28 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Да, если они нужны - лучше переопределить вручную.

2023-07-28 15:30 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +import lombok.*;
Люблю эту статью, прикладываю к каждой работе) Нужно где-то помечать, отправляла ли я ее или нет 🤔

2023-07-28 15:32 UTC, afomkina approved these changes

2023-07-28 15:32 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode(exclude = {"id"})
👍

2023-07-28 15:41 UTC, stasyaofit commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode(exclude = {"id"})
Анастасия, спасибо за ревью) Скажите, вы меня будете ревьюировать до конца обучения или до выхода моего ревьювера из отпуска?

2023-07-28 16:15 UTC, merged